name: Matrix Deploy

on:
  workflow_dispatch:
  
jobs:
  deploy:
    strategy:
      matrix:
        environment:
        - env1
        - env2
    runs-on: ubuntu-latest      
    steps:
      - name: 'hello world'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
