name: Matrix Deploy

on:
  workflow_call:
    inputs:
      environments:
        description: "Environments"
        type: string
  
jobs:
  deploy:
    strategy:
      matrix:
        environments: ${{ fromJson(inputs.environments) }}
    runs-on: ubuntu-latest      
    steps:
      - name: 'hello world'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
